### ISSUE TITLE
size_t not defined in rbtree.h

### ISSUE THREAD

**Issue by SylvAbdomen** [NetworkConfiguration/parpd#3]
When building on Arch Linux I get this compile error.
```
In file included from ../config.h:10,
                 from ../compat/rb.c:32:
../compat/rbtree.h:165:9: error: unknown type name ‘size_t’
  165 |         size_t rbto_node_offset;
      |         ^~~~~~
../compat/rbtree.h:53:1: note: ‘size_t’ is defined in header ‘<stddef.h>’; this is probably fixable by adding ‘#include <stddef.h>’
   52 | #include "endian.h"
  +++ |+#include <stddef.h>
   53 | #endif
```
  
To get this I ran `./configure --prefix=/usr --sbindir=/usr/bin --rundir=/run` then `make`.
   
If I add the include line to `rbtree.h` then the program compiles and functions properly.

**Comment by rsmarples** [comment]
The rbtree implementation has been removed in favour of verstable.
So this should now be fixed.
